project:
  type: website

website:
  title: "Global Salaries"
  description: "Analysis of global salaries based on education and experience."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: Data Analysis
      - href: graphic.qmd
        text: Graphic
      - href: formulas.qmd
        text: Mathematical Formulas
      - href: sources.qmd
        text: Sources
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
